#!/bin/env ruby

require 'json'

destination = ARGV.shift
payload = JSON.parse(ARGF.read)

raise 'There was no version specified' unless payload.dig('version')

Dir.chdir(destination) do
  urls = [payload['source']['urls']] unless payload['source'].fetch('urls').is_a?(Array)

  urls_with_versions = urls.map do |url|
    url.gsub(':version:', payload['version'].fetch('version'))
  end

  urls_with_versions.each do |url|
    warn "Downloading asset from #{url}"
    system("curl --remote-name #{url} 1>&2")
  end

  File.write('version', payload['version']['version'])
  File.write('urls', urls_with_versions.join("\n"))
end

puts payload.to_json
